# BÀI TẬP: E-COMMERCE DATA (ONLINE RETAIL)
**Nguồn:** kaggle.com/datasets/carrie1/ecommerce-data (541,909 dòng)

## Setup

In [2]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from scipy import stats

sns.set_style('whitegrid')

csv_path = 'https://raw.githubusercontent.com/databricks/Spark-The-Definitive-Guide/master/data/retail-data/all/online-retail-dataset.csv'

df = pd.read_csv(csv_path, encoding='ISO-8859-1', on_bad_lines='skip')
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
print('Loaded from:', csv_path)
df.head()

Loaded from: https://raw.githubusercontent.com/databricks/Spark-The-Definitive-Guide/master/data/retail-data/all/online-retail-dataset.csv

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

---
# PHẦN A — DATA PROFILING
## A.1. Data size, column names, data types

In [3]:
# TODO
# Data size kích thước dữ liệu
print("kích thước dữ liệu: ", df.shape)

kích thước dữ liệu:  (541909, 8)

In [ ]:
# Tên các cột (column names)
# Cách 1:
df.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country']

In [8]:
# Tên các cột (column names)
# Cách 2:
print("tên các cột: ", ", ".join(df.columns))

tên các cột:  InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country

In [13]:
# xem kiểu dữ liệu
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

## A.2. Missing values & Duplicate data

In [ ]:
# TODO
# Kiểm tra số lượng các giá trị bị thiếu (missing values)
print("Các giá trị bị thiếu: ", df.isnull().sum().sum())

Các giá trị bị thiếu:  136534

In [ ]:
# Kiểm tra số lượng các giá trị bị trùng (duplicated data)
print("Các giá trị bị trùng: ", df.duplicated().unique().sum())

Các giá trị bị trùng:  1

## A.3. Invalid values

In [27]:
# TODO
# Kiểm tra các giá trị không hợp lệ (invilid values)
print("Số lượng: ", (df['Quantity'] < 0).sum())
print("Đơn giá: ", (df['UnitPrice'] < 0).sum())
print("Mã đơn hàng: ", (df['InvoiceNo'].isnull().sum()))
print("Mã sản phẩm: ", (df['StockCode'].isnull().sum()))
print("Mã KH: ", (df['CustomerID'].isnull().sum()))

Số lượng:  10624
Đơn giá:  2
Mã đơn hàng:  0
Mã sản phẩm:  0
Mã KH:  135080

## A.4. Create a new column
Làm sạch dữ liệu (loại Quantity<=0, UnitPrice<=0), tạo cột `Sales` = Quantity * UnitPrice.

In [32]:
# TODO
df_clean = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)].copy()
df_clean

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [33]:
# tạo cột Sales
df['Sales'] = df['Quantity'] * df['UnitPrice']
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Sales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

---
# PHẦN B — DESCRIPTIVE STATISTICS
## Group 1 — Central Tendency

In [39]:
# TODO
# Giá trị trùng bình (mean)
mean_values = df[['Quantity', 'UnitPrice', 'Sales']].mean()
print(mean_values)

Quantity      9.552250
UnitPrice     4.611114
Sales        17.987795
dtype: float64

In [40]:
# Giá trị trung vị (median)
median_values = df[['Quantity', 'UnitPrice', 'Sales']].median()
print(median_values)

Quantity     3.00
UnitPrice    2.08
Sales        9.75
dtype: float64

In [41]:
mode_values = df[['Quantity', 'UnitPrice', 'Sales']].mode()
print(mode_values)

   Quantity  UnitPrice  Sales
0         1       1.25   15.0

## Group 2 — Dispersion

In [44]:
# TODO
df_clean['Sales'] = df_clean['Quantity'] * df_clean['UnitPrice']
cols = ['Quantity', 'UnitPrice', 'Sales']

# Range
range_vals = df_clean[cols].max() - df_clean[cols].min()
print(range_vals)

Quantity      80994.000
UnitPrice     13541.329
Sales        168469.599
dtype: float64

In [46]:
var_vals = df_clean[cols].var()
print(var_vals)

Quantity     24187.752994
UnitPrice     1289.936149
Sales        73092.768604
dtype: float64

In [47]:
std_vals = df_clean[cols].std()
print(std_vals)

Quantity     155.524124
UnitPrice     35.915681
Sales        270.356743
dtype: float64

In [49]:
q1 = df_clean[cols].quantile(0.25)
q3 = df_clean[cols].quantile(0.75)
iqr_vals = q3 - q1
print(iqr_vals)

Quantity      9.00
UnitPrice     2.88
Sales        13.95
dtype: float64

## Group 3 — Location and Shape

In [50]:
# TODO
# vị trí
q1 = df_clean[cols].quantile(0.25)
q2 = df_clean[cols].quantile(0.50) # Tương đương Median
q3 = df_clean[cols].quantile(0.75)

In [51]:
# hình dáng
skewness = df_clean[cols].skew()
kurtosis = df_clean[cols].kurt()

location_shape = pd.DataFrame({
    'Q1 (25%)': q1,
    'Q2 (50% - Median)': q2,
    'Q3 (75%)': q3,
    'Skewness (Độ lệch)': skewness,
    'Kurtosis (Độ nhọn)': kurtosis
})

print(location_shape)

           Q1 (25%)  Q2 (50% - Median)  Q3 (75%)  Skewness (Độ lệch)  \
Quantity       1.00               3.00     10.00          471.727716
UnitPrice      1.25               2.08      4.13          206.087555
Sales          3.75               9.90     17.70          506.706012

           Kurtosis (Độ nhọn)
Quantity        236462.342826
UnitPrice        62483.142715
Sales           297651.661046

---
# PHẦN C — DEFINE THE QUESTION

## Câu hỏi 1: Quốc gia nào đóng góp doanh thu cao nhất, chiếm bao nhiêu % tổng doanh thu?

In [52]:
# TODO
df['Sales'] = df['Quantity'] * df['UnitPrice']

country_sales = df.groupby('Country')['Sales'].sum()
total_sales = country_sales.sum()

country_summary = pd.DataFrame({
    'Doanh_thu': country_sales,
    'Ty_le_%': (country_sales / total_sales) * 100
}).sort_values(by='Doanh_thu', ascending=False)

top_country = country_summary.iloc[0]

print("QUỐC GIA CÓ DOANH THU CAO NHẤT")
print(f"Quốc gia: {country_summary.index[0]}")
print(f"Doanh thu: {top_country['Doanh_thu']:,.2f}")
print(f"Tỷ lệ chiếm: {top_country['Ty_le_%']:.2f}%")

print("\nTOP 5 QUỐC GIA")
print(country_summary.head())

QUỐC GIA CÓ DOANH THU CAO NHẤT
Quốc gia: United Kingdom
Doanh thu: 8,187,806.36
Tỷ lệ chiếm: 84.00%

TOP 5 QUỐC GIA
                  Doanh_thu    Ty_le_%
Country
United Kingdom  8187806.364  83.996903
Netherlands      284661.540   2.920280
EIRE             263276.820   2.700899
Germany          221698.210   2.274353
France           197403.900   2.025123

## Câu hỏi 2: Sản phẩm nào bán chạy nhất theo doanh thu?

In [53]:
# TODO
df['Sales'] = df['Quantity'] * df['UnitPrice']

product_sales = df.groupby(['StockCode', 'Description'])['Sales'].sum().reset_index()

top_products = product_sales.sort_values(by='Sales', ascending=False)

print("TOP 5 SẢN PHẨM CÓ DOANH THU CAO NHẤT (BAO GỒM PHÍ DỊCH VỤ)")
print(top_products.head(5).to_string(index=False))

non_products = ['DOT', 'POST', 'M', 'AMAZONFEE', 'BANK CHARGES', 'D']
filtered_products = top_products[~top_products['StockCode'].isin(non_products)]

print("\nTOP 5 MẶT HÀNG THƯƠNG MẠI CÓ DOANH THU CAO NHẤT")
print(filtered_products.head(5).to_string(index=False))

TOP 5 SẢN PHẨM CÓ DOANH THU CAO NHẤT (BAO GỒM PHÍ DỊCH VỤ)
StockCode                        Description     Sales
      DOT                     DOTCOM POSTAGE 206245.48
    22423           REGENCY CAKESTAND 3 TIER 164762.19
    47566                      PARTY BUNTING  98302.98
   85123A WHITE HANGING HEART T-LIGHT HOLDER  97715.99
   85099B            JUMBO BAG RED RETROSPOT  92356.03

TOP 5 MẶT HÀNG THƯƠNG MẠI CÓ DOANH THU CAO NHẤT
StockCode                        Description     Sales
    22423           REGENCY CAKESTAND 3 TIER 164762.19
    47566                      PARTY BUNTING  98302.98
   85123A WHITE HANGING HEART T-LIGHT HOLDER  97715.99
   85099B            JUMBO BAG RED RETROSPOT  92356.03
    23084                 RABBIT NIGHT LIGHT  66756.59

## Câu hỏi 3: Doanh số có tính mùa vụ theo tháng không?

In [11]:
# TODO

## Câu hỏi 4: Giá trị đơn hàng trung bình (Average Order Value) khác nhau thế nào giữa các quốc gia?

In [12]:
# TODO

## Câu hỏi 5: Tỷ lệ giao dịch có dấu hiệu trả hàng/hủy (Quantity âm ở dữ liệu gốc) khác nhau thế nào giữa các quốc gia?

In [13]:
# TODO

## Câu hỏi 6 (Tổng hợp) — Viết insight tổng hợp
Dựa trên Phần A, B, C, viết 4-5 câu insight tổng thể.

*(Viết insight của bạn vào đây...)*